### ISSUE TITLE
why not use `selectors` module appears in Python3.4?

### ISSUE THREAD

**Issue by jiajunhuang** [wiiiky/miserable#1]
Here it is: https://docs.python.org/3/library/selectors.html

I've read your Eventloop implementation, you're using Python3 to implement this project, so I think the module(`selectors`) is a better choice?

**Comment by wiiiky** [comment]
以后可以考虑

**Comment by wiiiky** [comment]
@jiajunhuang  你可以自己来重建

**Comment by jiajunhuang** [comment]
ok.

**Comment by jiajunhuang** [comment]
不过我拉下来跑了一下测试,没过?

```bash
$ python setup.py test
running test
running egg_info
writing top-level names to miserable.egg-info/top_level.txt
writing dependency_links to miserable.egg-info/dependency_links.txt
writing miserable.egg-info/PKG-INFO
writing entry points to miserable.egg-info/entry_points.txt
reading manifest file 'miserable.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README.rst'
writing manifest file 'miserable.egg-info/SOURCES.txt'
running build_ext
test_hostname (tests.address_test.HostnameTestCase) ... FAIL
test_cache (tests.cache_test.CacheTestCase) ... ok
test_socekt (tests.dns_test.DNSTestCase) ... ERROR

======================================================================
ERROR: test_socekt (tests.dns_test.DNSTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jiajun/Code/python/miserable/tests/dns_test.py", line 31, in test_socekt
    sock = Socket(servers)
  File "/home/jiajun/Code/python/miserable/miserable/dns/resolver.py", line 47, in __init__
    if hasattr(servers, '__iter__') else [ipv6_address(servers)]
  File "/home/jiajun/Code/python/miserable/miserable/dns/resolver.py", line 46, in <listcomp>
    self._servers = [ipv6_address(s) for s in servers]\
  File "/home/jiajun/Code/python/miserable/miserable/utils.py", line 43, in ipv6_address
    if ipaddr.version == 4:
AttributeError: 'NoneType' object has no attribute 'version'

======================================================================
FAIL: test_hostname (tests.address_test.HostnameTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jiajun/Code/python/miserable/tests/address_test.py", line 30, in test_hostname
    self.assertTrue(addr.ipaddr is not None)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 3 tests in 1.606s

FAILED (failures=1, errors=1)
```

**Comment by wiiiky** [comment]
用Python3跑，另外DNS的测试依赖网络。

**Comment by wiiiky** [comment]
已经使用selectors重新实现主循环
@jiajunhuang

**Comment by jiajunhuang** [comment]
嗯，好。最近在考驾照😅
